#version: '3.8'
#services:
#  db:
#    image: postgres:15.0
#    restart: always
#    container_name: parceltracker
#    environment:
#      - POSTGRES_USER=pguser
#      - POSTGRES_PASSWORD=pgpassword
#      - POSTGRES_DB=parceltrackerdb
#    ports:
#      - '5432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
#volumes:
#  db:
#    driver: local